version: '3.8'

services:
  backend:
    image: 440744254638.dkr.ecr.us-east-1.amazonaws.com/estate-backend
    container_name: estate-backend
    ports:
      - "3000:3000"
    env_file:
      - /home/ec2-user/envfolder/.env
    restart: always

  frontend:
    image: 440744254638.dkr.ecr.us-east-1.amazonaws.com/estate-frontend
    container_name: estate-frontend
    ports:
      - "4000:80"
    env_file:
      - /home/ec2-user/envfolder/.env
    restart: always
    depends_on:
      - backend
