version: '3.8'

services:
  backend:
    image: udaykiranchilumula/estate-backend:${TAG}
    container_name: estate-backend
    ports:
      - "3000:3000"
    env_file:
      - /home/ec2-user/envfolder/.env
    restart: always

  frontend:
    image: udaykiranchilumula/estate-frontend:${TAG}
    container_name: estate-frontend
    ports:
      - "4000:80"
    env_file:
      - /home/ec2-user/envfolder/.env
    restart: always
    depends_on:
      - backend
